---
title: "viz_part1"
author: "Ze Li"
date: "2023-09-28"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

Get the data for plotting today.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Let's make a plot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point()
```

### Pipes and stuff

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

ggp_nyc_weather = 
  weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

ggp_nyc_weather 
```



## Fancy plot

```{r}
ggplot(weather_df, aes(x= tmin, y = tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth()

ggplot(weather_df, aes(x= tmin, y = tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)

ggplot(weather_df, aes(x= tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3) +
  geom_smooth(se = FALSE)
```

### facets

Plot with facets

```{r}
ggplot(weather_df, aes(x= tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  facet_grid(. ~ name)

ggplot(weather_df, aes(x= tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  facet_grid(name ~ .)
```

Let's try a different plot. temps are boring

```{r}
ggplot(weather_df, aes(x= date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth() +
  facet_grid(. ~ name)
```

try assigning a specific color

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = date, y = tmax)) +
  geom_point(color = "blue")

weather_df |> 
  filter(name != "CentralPark_NY") |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.7, size = 0.5)
```

### hex plot

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

### line

```{r}
weather_df |> 
  filter(name == "Molokai_HI") |>
  ggplot(aes(x = date, y = tmax)) +
  geom_line(alpha = .5) +
  geom_point(size = .5)
```



## univariate plotting

### histogram

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge")
```

### density plot

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3, adjust = .75)
```

### box plot

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_boxplot()
```

### violin plot

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_violin()
```

### ridge plot

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```

