---
title: "viz_part2"
author: "Ze Li"
date: "2023-10-03"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#theme_set(theme_minimal() + theme(legend.position = "bottom"))

#options(
#  ggplot2.continuous.colour = "viridis",
#  ggplot2.continuous.fill = "viridis"
#)

#scale_colour_discrete = scale_colour_viridis_d
#scale_fill_discrete = scale_fill_viridis_d
```

Get the data for plotting today.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

This results in a dataframe with `r nrow(weather_df)` observations on six variables.

## Same plot from last time

### rename variables & scale

```{r}
weather_df |>
  #filter(tmax >= 20, tmax <= 30) |>
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha= .5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp (Degrees C)",
    color = "Location",
    caption = "Max vs Min daily temp in three locations; data from rnoaa"
  ) +
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15", "0", "15")
  ) +
  scale_y_continuous(
    position = "right",
    trans = "sqrt", # transformation
    #limits = c(20,30)
  )
```

### colors 

what about colors...

```{r scale_color_hue; viridis}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha= .5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp (Degrees C)",
    color = "Location",
    caption = "Max vs Min daily temp in three locations; data from rnoaa"
  ) +
  #scale_color_hue(h = c(150,200))
  viridis::scale_color_viridis(discrete = TRUE)
```



## Themes

```{r }
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha= .5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp (Degrees C)",
    color = "Location",
    caption = "Max vs Min daily temp in three locations; data from rnoaa"
  ) +
  viridis::scale_color_viridis(discrete = TRUE) +
  theme_minimal() + # bw & without box lines
  #theme_classic() + # no grid line (recommend with grid line)
  #theme_bw() +
  theme(legend.position = "bottom") # legend bottom should be lower than bw (bw will reset)
```


## data arguments ...

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth()

nyc_weather_df = 
  weather_df |>
  filter(name == "CentralPark_NY")

hawaii_weather_df = 
  weather_df |>
  filter(name == "Molokai_HI")

ggplot(nyc_weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = hawaii_weather_df)
```



## `patchwork`

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  facet_grid(. ~ name)
```

```{r}
ggp_temp_scatter =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |>
  filter(prcp > 25) |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) +
  theme(legend.position = "none")

ggp_tmax_date = 
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom")

(ggp_temp_scatter + ggp_prcp_density) / ggp_tmax_date
```



## data manipulation - relevel / reorder

```{r}
weather_df |>
  mutate(
    name = fct_relevel(name, c("Molokai_HI","CentralPark_NY","Waterhole_WA"))
  ) |>
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

weather_df |>
  mutate(
    name = fct_reorder(name, tmax)
  ) |>
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin()
```



## complicate FAS plot

```{r}
litter_data = 
  read_csv("data/FAS_litters.csv") |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

pup_data = 
  read_csv("data/FAS_pups.csv") |>
  janitor::clean_names() #|>
  #mutate(
  #  sex = 
  #    case_match(
  #      sex, 
  #      1 ~ "male", 
  #      2 ~ "female"))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number") 

fas_data |> 
  select(dose, day_of_tx, starts_with("pd")) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome", 
    values_to = "pn_day") |> 
  drop_na() |> 
  mutate(outcome = fct_reorder(outcome, pn_day)) |> 
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() + 
  facet_grid(day_of_tx ~ outcome)
```

